# 数据库连接配置
server:
    #本地端口
    port: 8091
spring:
    datasource:
        #数据库账号密码
        url: jdbc:p6spy:mysql://192.168.5.139:3306/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8
        username: remote_user
        password: 1234
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#sql日志打印
decorator:
    datasource:
        p6spy:
            # 日志格式
            log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
            # 自定义日志类
            logging: custom
            custom-appender-class: com.project.wms.common.StdoutLogger
#mybatis-plus:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
    config:
        DouBaoApiKey: "d399d950-e898-4155-bb0a-8d8f00bdd3a5"
        baseUrl: "https://ark.cn-beijing.volces.com/api/v3/"
        model: "ep-20241125221621-wqp4t"
        botId: "bot-20241125225426-wzcrl"
wechat:
    config:
        url: "http://192.168.5.139:3001/webhook/msg/v2?token=dingxhui"


