# 数据库连接配置
server:
    #本地端口
    port: 8090
spring:
    datasource:
        #数据库账号密码
        url: jdbc:p6spy:mysql://127.0.0.1:3306/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8
        username: root
        password: Ab660855
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#sql日志打印
decorator:
    datasource:
        p6spy:
            # 日志格式
            log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
            # 自定义日志类
            logging: custom
            custom-appender-class: com.project.wms.common.StdoutLogger
#mybatis-plus:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

